---
title: "Unit 1 FLS"
author: "Banu"
date: "2023-01-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
population = rnorm(10000000,0,1)
hist(population)
population = rchisq(10000000,2)
hist(population)
summary(population)
sd(population)

sample1 = sample(population,50)
hist(sample1)
summary(sample1)
sd(sample1)
mean(sample1)
n1=50
simulations=10000
xbar_holder1=numeric(simulations)
for (i in 1:simulations)
{ 
sample1 = sample(population,n1)
xbar1 = mean(sample1)
xbar_holder1[i] = xbar1
}

hist(xbar_holder1, col = "blue", main = paste("Distribution of the sample mean: n = ", n1), xlab = "Dist 1 Sample Means", xlim = c(-4,4))

summary(xbar_holder1)
sd(xbar_holder1)
hist(xbar_holder1, col = "blue", main = paste("Distribution of the sample mean: n = ", n1), xlab = "Dist 1 Sample Means")
Beach_Comber_age = c(25,19,37,29,40,28,31)
summary(Beach_Comber_age)
sd(Beach_Comber_age)
t.test(Beach_Comber_age, mu = 21)

hist(Beach_Comber_age)
(mean(Beach_Comber_age) - 21)/(sd(Beach_Comber_age)/sqrt(6))
(mean(Beach_Comber_age) - 21)/(sd(Beach_Comber_age)/sqrt(7))

```